FROM microsoft/mssql-server-windows-express
LABEL Description="SQL Server" Vendor="Microsoft" Version="2016 SP1"
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]

# SQL environmental variables
ENV sa_password Tr#dne1-Has!o2
ENV attach_db []

# Copy SQL scripts for setting up blog database and tables
COPY . /

WORKDIR /

# Create blog application database and tables
RUN New-Item C:\data -Type Directory
RUN sqlcmd -S localhost,1433 -i Setup-BlogDatabase.sql
RUN sqlcmd -S localhost,1433 -i Setup-BlogTables.sql

CMD powershell ./start -sa_password $env:sa_password -attach_dbs $env:attach_dbs -Verbose